# Generated by Django 4.2.8 on 2024-02-16 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=255)),
                ("artiste", models.CharField(max_length=255)),
                ("audio_file", models.FileField(upload_to="audio_files/")),
                ("title", models.CharField(max_length=255)),
                ("cover_image", models.CharField(max_length=255)),
                ("terms_condition", models.BooleanField(default=False)),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AudioSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                (
                    "segment_file",
                    models.FileField(
                        blank=True, null=True, upload_to="audio_segments/"
                    ),
                ),
                ("transcription", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("duration", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "audio_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="audojifactory.audiofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSelectedAudoji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audojifactory.audiosegment",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "audio_segment")},
            },
        ),
    ]
