# Generated by Django 4.2.8 on 2024-01-04 20:34

import audojifactory.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("audojifactory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="artiste",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="audiosegment",
            name="segment_file",
            field=models.FileField(
                upload_to=audojifactory.models.get_segment_upload_path
            ),
        ),
    ]
