# Generated by Django 4.2.8 on 2024-02-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audojifactory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiosegment",
            old_name="mood",
            new_name="category",
        ),
    ]
