# Generated by Django 4.2.8 on 2024-02-14 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("audojifactory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSelectedAudoji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audojifactory.audiosegment",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_id", "audio_segment")},
            },
        ),
    ]
