# Generated by Django 4.2.8 on 2024-02-19 08:34

import audojifactory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audojifactory", "0002_alter_audiofile_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiosegment",
            name="segment_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=audojifactory.models.get_segment_upload_path,
            ),
        ),
    ]
