# Generated by Django 4.2.8 on 2024-01-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audojifactory", "0002_audiofile_artiste_alter_audiosegment_segment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosegment",
            name="mood",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
