# Generated by Django 4.2.8 on 2024-02-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audojifactory", "0002_userselectedaudoji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiosegment",
            name="segment_file",
            field=models.FileField(blank=True, null=True, upload_to="audio_segments/"),
        ),
    ]
