# Generated by Django 4.2.8 on 2024-04-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audojifactory", "0003_alter_audiosegment_segment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
