# Generated by Django 4.2.8 on 2024-04-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audojifactory", "0004_audiofile_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="spotify_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
