# Generated by Django 4.2.8 on 2024-01-24 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audojifactory", "0004_audiofile_cover_image_audiofile_terms_condition"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiofile",
            old_name="file",
            new_name="audio_file",
        ),
        migrations.RenameField(
            model_name="audiofile",
            old_name="user",
            new_name="owner",
        ),
    ]
