# Generated by Django 4.2.8 on 2024-04-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audojifactory", "0005_audiofile_spotify_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="audiosegment",
            name="category",
        ),
    ]
