# Generated by Django 4.2.8 on 2024-04-17 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("audojifactory", "0006_category_remove_audiosegment_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiosegment",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="audojifactory.category",
            ),
        ),
    ]
