# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set environment variables to reduce Python bytecode generation and unbuffered logging
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install build dependencies, ffmpeg, and git in a single RUN statement to reduce layers
# Also, combine apt-get update with apt-get install and cleanup to reduce image size
RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg git && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /code

# Copy project
COPY . /code/

RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir git+https://github.com/openai/whisper.git

# Run the application
CMD ["daphne", "audojiengine.asgi:application", "--port", "$PORT", "--bind", "0.0.0.0"]
